### ISSUE TITLE
Rails 5.0.0.beta1 breaks high_voltage gem

### ISSUE THREAD

**Issue by DanielKehoe** [RailsApps/learn-rails#76]
Using Rails 5.0.0.beta1, the high_voltage gem breaks, when I attempt to visit the About page, with error:
```
ActionController::RoutingError at /pages/about
undefined method `hide_action' for HighVoltage::PagesController:Class
```

**Comment by DanielKehoe** [comment]
Issue reported:
https://github.com/thoughtbot/high_voltage/issues/220

**Comment by DanielKehoe** [comment]
Rails 5.0.0.beta2 is out and the high_voltage gem is still broken.

**Comment by kwibus2000** [comment]
Is the fix in Rails 5.0.0.1 ?

**Comment by DanielKehoe** [comment]
The newest released version of the high_voltage works fine with Rails 5.0.
